import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next"

const jesofin = Josefin_Sans({
  variable: "--font-jesofin",
});

export const metadata: Metadata = {
  title: "ghwrap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jesofin.className} antialiased`}>{children}
      <Analytics/>

      </body>
    </html>
  );
}
